name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # --- Essential Settings ---
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }} # Uses the owner of the repo (you)

          # --- Control the overall layout/sections ---
          base: header, activity, community, repositories, metadata

         # --- Enable & Configure Plugins ---
          plugin_achievements: yes
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          
          # --- File Output ---
          # This will generate a file named 'metrics.svg' in a folder called 'github-metrics'
          filename: github-metrics/metrics.svg
          # This ensures the SVG is committed to your main branch
          output: readme
